packages:
  - fixtures/*

overrides:
  '@eslint-community/eslint-utils': ^4.7.0
  '@typescript-eslint/utils': ^8.34.0
  eslint: ^9.28.0
  tsx: ^4.19.4

catalogs:
  dev:
    '@antfu/ni': ^25.0.0
    '@eslint-react/eslint-plugin': ^1.51.3
    '@eslint-types/typescript-eslint': ^7.5.0
    '@eslint-types/unicorn': ^52.0.0
    '@eslint/config-inspector': ^1.1.0
    '@prettier/plugin-xml': ^3.4.1
    '@stylistic/eslint-plugin-migrate': ^4.4.1
    '@types/node': ^24.0.0
    '@types/react': ^19.1.7
    '@unocss/eslint-plugin': ^66.1.4
    bumpp: ^10.1.1
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    eslint-typegen: ^2.2.0
    esno: ^4.8.0
    execa: ^9.6.0
    lint-staged: ^16.1.0
    prettier: ^3.5.3
    react: ^19.1.0
    simple-git-hooks: ^2.13.0
    simple-open-url: ^3.0.1
    sucrase: ^3.35.0
    tinyglobby: ^0.2.14
    tsdown: ^0.12.7
    typescript: ^5.8.3
    vue: ^3.5.16
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint/markdown': ^6.5.0
    '@stylistic/eslint-plugin': ^4.4.1
    '@typescript-eslint/eslint-plugin': ^8.34.0
    '@typescript-eslint/parser': ^8.34.0
    '@vitest/eslint-plugin': ^1.2.1
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.1.0
    eslint-merge-processors: ^2.0.0
    eslint-parser-plain: ^0.1.1
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-import-x: ^4.15.1
    eslint-plugin-jsdoc: ^50.7.1
    eslint-plugin-jsonc: ^2.20.1
    eslint-plugin-n: ^17.19.0
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^4.14.0
    eslint-plugin-pnpm: ^0.3.1
    eslint-plugin-regexp: ^2.9.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^59.0.1
    eslint-plugin-unused-imports: ^4.1.4
    eslint-plugin-vue: ^10.2.0
    eslint-plugin-yml: ^1.18.0
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^16.2.0
    jsonc-eslint-parser: ^2.4.0
    local-pkg: ^1.1.1
    prompts: ^2.4.2
    toml-eslint-parser: ^0.10.0
    vue-eslint-parser: ^10.1.3
    yaml-eslint-parser: ^1.3.0
  test:
    vitest: ^3.2.3

onlyBuiltDependencies:
  - simple-git-hooks
peerDependencyRules:
  ignoreMissing:
    - prettier
